### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by JustinRR** [nlhans/ets2-sdk-plugin#10]
Just wondering if this project will be updated to include new updates to telemetry from SCS? Thank you!

**Comment by yodek** [comment]
At website of ETS2 I see updated link, now is SDK v1.5 - http://download.eurotrucksimulator2.com/scs_sdk_1_5.zip

**Comment by JustinRR** [comment]
Didn't see it, calm down.

**Comment by nlhans** [comment]
I've managed to get some time today after formatting my PC and changing my workflow a bit.
Release 1.3.0: https://github.com/nlhans/ets2-sdk-plugin/releases/tag/revision_4_rel_1_3_0
