### ISSUE TITLE
C++ project?

### ISSUE THREAD

**Issue by dualznz** [nlhans/ets2-sdk-plugin#13]
hi love the telementary, i know c# but i dont know c++ is there anyway you can provide the demo C# project source so that i am able to extract data from it to create a elementary package for my group..

**Comment by nlhans** [comment]
The plugin using the SDK is written in C++. I am unaware of any options to run C# in ETS2, hence the C++ plugin was written to bridge that gap to external applications.

There is a demo client available in the source repository and release that is written in C#. See the folder ets2-client/C#/ in the source browser.
