### ISSUE TITLE
C# Telemetry speed limit not working

### ISSUE THREAD

**Issue by tonsmets** [nlhans/ets2-sdk-plugin#14]
Hi there!

While working with the awesome Telemetry software you have in this repo, I stumbled upon the fact that data.Job.SpeedLimit isn't working. It simply returns 0 while playing ETS2.

Is this a known issue or am I forgetting something? All other data works.

I hope to hear from you!

**Comment by nlhans** [comment]
The speedlimit should return in m/s. I'm using the field in my own application as a hard speed limiter.
When there is no speedlimit (e.g. a parking lot) it returns -1.

I'm not sure exactly, but maybe you have not enabled the speedlimit display on the in-game nav map? There are 3 options: off, truck limit, car limit. It seems like the SDK will report the value that is displayed there.

**Comment by tonsmets** [comment]
I can see the speed limit in-game on the navigation, so that setting is OK I guess. What version of ETS2 and what version of the SDK are you using? My application reports SDK version 4 and ETS2 version 1.10. I'm also running the Oculus Rift beta 1_16.

**Comment by nlhans** [comment]
The speed limit field was added in ETS2 SDK version 1.5.
That SDK version is shipped with game version 1.17

**Comment by tonsmets** [comment]
Thanks for your reply! Unfortunately there is still no Oculus Rift support on that game version :(. Thanks for your help!

**Comment by tonsmets** [comment]
UPDATE: I used the normal "oculus" branch instead of the "oculus_1_16_02" branch... Pretty easy fix and I feel stupid for not trying this earlier on...
