### ISSUE TITLE
Telemetry.dll compiled (from sdk 1.5) but doesn't make log file

### ISSUE THREAD

**Issue by RagoIcarus** [nlhans/ets2-sdk-plugin#15]
I have compiled the SDK 1.5 with VS2013 and put it into the plugins folder of my x86 (windows 8.1 Pro),

Now it doesn't create the log file or write to the log file if I have made the log file myself.
Did I do something wrong? I must say that I find the documentation quite depressing.

**Comment by nlhans** [comment]
What kind of log file do you expect? It does not so by default.
The "log function" (which is a debug function at best) is not something intended for end users to use.

Remember that this is a fan created plug-in.
