### ISSUE TITLE
Game Time 

### ISSUE THREAD

**Issue by RenCloud** [nlhans/ets2-sdk-plugin#17]
Is it possible to add the game time to the data?

**Comment by nlhans** [comment]
Do you mean this? https://github.com/nlhans/ets2-sdk-plugin/blob/master/ets2-telemetry/inc/ets2-telemetry-common.hpp#L28

Or do you actually mean the in-game time in hours/minutes/seconds? I have never really taken a look at how the integer should be pulled apart, really.
Maybe this is useful; it seems like the time is stored in absolute minutes:
https://github.com/Funbit/ets2-telemetry-server/blob/master/source/Funbit.Ets.Telemetry.Server/Data/Ets2TelemetryData.cs#L88

**Comment by RenCloud** [comment]
I mean the second. 
But i found a solution ^^. Thx

**Comment by Patrick-van-Halm** [comment]
@RenCloud Can I maybe get your solution as 
`internal static DateTime SecondsToDate(int seconds)
        {
            if (seconds < 0) seconds = 0;
            return new DateTime((long)seconds * 10000000, DateTimeKind.Utc);
        }

        internal static DateTime MinutesToDate(int minutes)
        {
            return SecondsToDate(minutes * 60);
        }`
this doesnt work cause its an unsigned int but when i try converting it i get the wrong time

**Comment by RenCloud** [comment]
@Patrick-van-Halm  if you are still interested in this look my answer in #21 may it help. If not write it in the issue there or ask me directly.
