### ISSUE TITLE
Boolean problem?

### ISSUE THREAD

**Issue by killar34** [nlhans/ets2-sdk-plugin#2]
Hello, I'm trying to add a few more outputs, but having a problem with booleans...
The first boolean works fine, but when I add a second boolean, it overrides the first one (and on and on, no matter how many are added).
Floats for other values (like oil pressure) work fine.

Do you have any idea what might be wrong?

**Comment by nlhans** [comment]
Booleans have always been problematic to use, if your problem still persists (I know, this response is very late), please try out one of the later revisions of the plugin where I added a whole lot of boolean fields. It may already be added what you wanted to do.
