### ISSUE TITLE
refrencing dll to application

### ISSUE THREAD

**Issue by dualznz** [nlhans/ets2-sdk-plugin#20]
Hi all
Im tying to better understand this dll lib, what im trying to do is allow the user to select their ETS2 directory then it will carry on to listen to /win_x86/plugins/lib.dll

as we all know people may have their instance of ets2 outside of c:\

so my question is, can we talk to the dll by DLLIMPORT or some other means so then we can use the lib without having to explicit add it to the application.

which will in tail allow people to not be confined to c:\ for the usage of this dll in a application.

**Comment by nlhans** [comment]
It is not required to add the DLL to your client program. This plugin for ETS2 SDK uses memory mapped files to transfer data, so the cilent and plugin can operate without any path references.

**Comment by dualznz** [comment]
hmmm ok, but how can i talk to it within my application, as i am calling like data.clientsdkversion and so forth.

im abit new to dll and memory mapping

cheers

**Comment by dualznz** [comment]
im not sure on how to add memory mapped file for this sdk, i did memorymappedfile.createfromfile() but it does not work, i know vb.net and c# but i have never worked with memorymapping and there is no documentation on it.

cheers

**Comment by dualznz** [comment]
is nobody willing to give an insite in how to access the shared memory for this plugin?

**Comment by nlhans** [comment]
I think it's first off most important to familiarize yourself with the difference between DLLs and Shared Memory.

Shared Memory are a form of IPC provided by Windows. It creates virtual files that can be read from multiple applications with no handshaking. This allows for an easy "announcement" of the telemetry data across applications on your local machine.
This plugin provides this functionality via the DLL. It does the translation from SCS SDK to a fixed shared memory map. This DLL is intended to be run with the SDK environment of SCS games and should be installed into the game only. You do not reference this from your client application.

A client implementation can instead use or be based on the demo application. A full .NET implementation written in C# is available on the repository. It is made to show what data fields are available, and the code is available for re-use in other OSS projects.
