### ISSUE TITLE
Get Money

### ISSUE THREAD

**Issue by MogliDerZauberKoenig** [nlhans/ets2-sdk-plugin#23]
How can i get the value of my money with the SDK?

**Comment by yodek** [comment]
http://forum.scssoft.com/viewtopic.php?p=519023#p519023 - at this moment you CAN'T, Telemetry API by plugin doesn't provide that info.

**Comment by nlhans** [comment]
Unfortunately the SCS SDK does not provide this value to the plugin.
Therefore it can not be reported or supported at this moment.
