### ISSUE TITLE
From which version this plugin works.

### ISSUE THREAD

**Issue by raul2015** [nlhans/ets2-sdk-plugin#24]
I installed version 1.1.1 and did the steps to use the sdk but it doesn't show anything in the sample app. Could you tell if this is for the version and from which one will it work?

**Comment by nlhans** [comment]
Have you installed the plug-in DLL at the folder said by the readme?
Do you get a message box on start-up saying SDK functions are enabled?
Which version of the Steam game are you running?
Are you running the sample app on the same PC, and tried to run it as an administrator (may be needed if you run games as admin as well).

**Comment by raul2015** [comment]
Have you installed the plug-in DLL at the folder said by the readme? Yes, I did
 Do you get a message box on start-up saying SDK functions are enabled? No, it starts as usual. I have version 1.1.1 of the game, this has something to do ? 
 Which version of the Steam game are you running? No, The version of the game I have is not in steam
 Are you running the sample app on the same PC, and tried to run it as an administrator (may be needed if you run games as admin as well). I did it


My doubt is if the game version has something to do with the plugin working or not. The game installation is a bit more than 500MB. Once installed is 1.5GB.


Regards,

**Comment by nlhans** [comment]
Very old versions of the game do not support SDK. Not getting the dialog message on start-up confirms that.
I would suggest upgrading your copy to the latest version over Steam. If you have a license key you can enter it in Steam and it will update to the latest version available. I think we're already at 1.22, so about 21 verions further ahead.

**Comment by raul2015** [comment]
Will the sdk work with the latest game version out of steam ?

---- On Thu, 18 Feb 2016 02:39:25 -0500 Hans &lt;notifications@github.com&gt; wrote ---- 

Very old versions of the game do not support SDK. Not getting the dialog message on start-up confirms that.
 I would suggest upgrading your copy to the latest version over Steam. If you have a license key you can enter it in Steam and it will update to the latest version available. I think we're already at 1.22, so about 21 verions further ahead.

**Comment by nlhans** [comment]
Yes

**Comment by yodek** [comment]
1.1.1? I thought you were talking about ATS, not ETS2 :)
