### ISSUE TITLE
Build a 64 bit version

### ISSUE THREAD

**Issue by cdante100** [nlhans/ets2-sdk-plugin#27]
Hi, I have a problem, I have this code to generate a telemetry plugin for ETS2, just that I only work on 32-bit ETS2, can help me build a version for ETS2 64-bit? [CODE](http://downloads.silasparker.co.uk/ets2_dashboard_v3.zip)
@nlhans

**Comment by nlhans** [comment]
Sorry I cannot. I did not write said project, additionally it uses a different toolchain (or lack of any; so to speak).

I suggest to open a ticket on the respective repository; which could have been found within 2 minutes of googling: https://github.com/skyhisi/ets2_dashboard/blob/master/build/build.bat
