### ISSUE TITLE
Broken .DLL file

### ISSUE THREAD

**Issue by DarkhejMaster** [nlhans/ets2-sdk-plugin#28]
The ets2sdkclient .dll does no longer work.
Game log: [http://pastebin.com/s5fMS77N](pastebin.com)

**Comment by nlhans** [comment]
You have placed the wrong DLL in the directory.

You need to place the ets2-telemetry.dll inside the plugins folder. The "Ets2SdkClient.dll" is a plugin for developers.

**Comment by DarkhejMaster** [comment]
Ok thank you.  Then I know.
