### ISSUE TITLE
Error on plugin load

### ISSUE THREAD

**Issue by yugecin** [nlhans/ets2-sdk-plugin#37]
I made a program using this, but the plugin doesn't work for someone and I can't find out why.
The game starts and plugin doesn't work (no popup with sdk blabla), in the game.log.txt there is something like this:
```
00:00:09.161 : loading 'ets2-telemetry' 'C:/SteamLibrary/steamapps/common/Euro Truck Simulator 2/bin/win_x64/plugins/ets2-telemetry.dll'
00:00:09.162 : <ERROR> 0x00007E
```
I saw that the person with this problem has a fairly new pc, perhaps it is because of missing c++ redistributable packages?
Neither 32 or 64 bit work, os is win10

**Comment by c0nnex** [comment]
If Visual Studio and ETS on same computer the redistributable should not be a problem. 
If they are on diffrent computers, the redistributable must be installed (the one belonging to the toolset you use when building)

Error 0x00007E means "The specified procedure could not be found." btw. 
Did you play around with the exports?
You MUST export "scs_telemetry_init" and "scs_telemetry_shutdown"

**Comment by yugecin** [comment]
I took the prebuilts from the releases

**Comment by c0nnex** [comment]
Then missing redistributables is most likely the problem.

**Comment by Koenvh1** [comment]
It indeed sounds like a missing redistributable, this one probably: https://www.microsoft.com/en-gb/download/details.aspx?id=48145

**Comment by yugecin** [comment]
I'm not getting any replies anymore from the person, but it probably fixes it. I think it would be either the 2012 or 2015 ones (depends made me believe it should be the 2012 ones).
