### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by TheAifam5** [nlhans/ets2-sdk-plugin#4]
This is compatible with Linux ETS2?

**Comment by nlhans** [comment]
The current revisions are DLLs and only run on Windows.

I am unaware of any support for SDK plugins in ETS2 for Linux neither. All SDK examples are for Windows, and they also use Windows-specific includes in their code.
I don't run Linux as a gaming OS at this moment, so I haven't got ETS2 installed to try this out. 

If you do have any related links to the ETS2 SDK and Linux, please let me know.
