### ISSUE TITLE
Reading current Torque

### ISSUE THREAD

**Issue by hakodeveloper** [nlhans/ets2-sdk-plugin#44]
Hi, 

I'm developing a companion app to help me drive more efficiently, but for it to work I need a way of reading the current torque applied by the engine, or at least a way of knowing the current gear ratio. Is there any way of reading said value? I would be awesome if the SDK could provide those values.

Thanks.

**Comment by pcnorden** [comment]
Hi there!
I have come up with 2 ways to get what you are asking.

1. Simple formula to get the torque of the engine, namely `(hp*5252)/rpm=torque` is the formula.
With that said, the SDK doesn't say how much horsepower the engine has, so what you can probably do is take the model and manufacturer of the truck and cross reference that to a list of trucks where you have defined them, then take the number that you got from that, and use that in the formula above.
2. Under the drivetrain, you can access a variable called `GearRatiosForward` and `GearRatiosReverse`. In that case, you only need to check what gear you are in (example: 11) and then just fetch the gear ratio from the list. But beware that you will need some handling.
Some pseudo-code:
```
public static int getRatio(int currentGear){
    if(currentGear > 0){
        return gearRatiosForward[currentGear-1]
    }else if(currentGear < 0){
        return gearRatiosReverse[(currentGear*-1)-1]
    }else{
        return null;
    }
}
```

Hope that this helps!

**Comment by nlhans** [comment]
That formula is a conversion between power and torque+rpm, which doesn't say anything about the torque curve of the engine.

Old versions of ETS2 generated torque curves. I modelled this polynomial years ago that seemed to match quite well, but not perfect: https://github.com/nlhans/SimShift/blob/master/SimShift/SimShift/Models/Ets2Drivetrain.cs#L28
Newer versions of ETS2 support custom torque tables. I don't think the SDK lets you enumerate over these tables, so you would need to extract these from the SCS game or mod files.

**Comment by hamzaaladwan** [comment]
What this?!
