### ISSUE TITLE
Report nearest city.

### ISSUE THREAD

**Issue by AdamorfuX** [nlhans/ets2-sdk-plugin#45]
Hi.

I am just wondering is it possible to add the nearest city to the plugin. Like when you press f7 + enter and it shows to the whitch city it's gonna to teleport you?.

**Comment by Koenvh1** [comment]
No idea whether the SDK supports it, but you can do it manually based on your coordinates and the coordinates of all cities. If you need to generate a list of all cities with coordinates: https://github.com/Koenvh1/ETS2-City-Coordinate-Retriever

**Comment by AdamorfuX** [comment]
Ok thanks
