### ISSUE TITLE
Fuel warning not a boolean

### ISSUE THREAD

**Issue by schumi1331** [nlhans/ets2-sdk-plugin#5]
It seems that the fuel warning value is not working because it is declared in your plugin as a float, though this is a boolean in the SCS sdk.

**Comment by nlhans** [comment]
Thanks for reporting this issue. It was indeed incorrect, I've now changed the field to an int so the struct maintains it's byte layout.
The C# struct ETS2Telemetry.Drivetrain has a new field FuelWarningLight. The old FuelWarning field is deprecated.

**Comment by leedonald54** [comment]
In the rear end ,in the back there is not there , if you lift the  wheel on the front tantrum ,you will not have a drive wheel , as there no back rear end just a bar , if  look at World of trucks I put pictures of what I am talking about . On a normal you drive through the first one ,then Lock in Drivers , so if you want to lift , you could drive and lift them , but you need to be able to slide your fifth wheel back , so under drive wheel . I hope you look at Pictures . It is only on new Volvo FH, If drove trucks would spot and  ,I BET so would the Company .

**Comment by leedonald54** [comment]
Not in telemetry . I building & a BUG .

**Comment by yodek** [comment]
@leedonald54 You should find a better way to translate instead using Google.Translate.

**Comment by leedonald54** [comment]
How do you repot a BUG ?

**Comment by leedonald54** [comment]
And I do not use GOOGLE or translate , I am using good old English .
