### ISSUE TITLE
hi, ineed some help.

### ISSUE THREAD

**Issue by neonil123** [nlhans/ets2-sdk-plugin#56]
i'm trying to make an external cluster for the game with arduino. i have installed the dll file but i don't understand how to make a simple program that gets the data (i need a console program that can read the data ) . Sorry but i don't know  a lot about c#

**Comment by Koenvh1** [comment]
Take a look at the C# demo program: https://github.com/nlhans/ets2-sdk-plugin/tree/master/ets2-client/C%23 
It should give you an insight in how it works 😉 
I don't believe you need anything special to compile the demo - just Visual Studio should suffice.

**Comment by neonil123** [comment]
thanks for the support :)  
the c# demo works perfectly with visual studio

**Comment by neonil123** [comment]
what is the difference between sdkclient and sdkclient.demo
i can compile only sdkclient.demo
![Annotazione 2019-08-06 155112](https://user-images.githubusercontent.com/38853538/62541237-162f1180-b862-11e9-8b49-5294b2f42f7b.png)

**Comment by RenCloud** [comment]
The demo is an ui application to show how to use the client. 

The client is a library that gets the data from the shared memory and creates an object which contains the data. You need to reference this in your own project to get the data.

**Comment by neonil123** [comment]
thanks a lot !!! 
now i understand how it works :)

**Comment by neonil123** [comment]
i need a simple program (just to output data in the console)
but i dont know how to read data from the object.
this is my code.
can you give me an example of how to get daa (create propper object and use it)

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Ets2SdkClient;

namespace fdggdf
{

class Program
{
    //Ets2SdkClient.Ets2SdkTelemetry Telemetry = new Ets2SdkClient.Ets2SdkTelemetry();
    Ets2SdkClient.Ets2Telemetry._Physics a = new Ets2SdkClient.Ets2Telemetry._Physics();
    Ets2SdkClient.Ets2Telemetry._Drivetrain b = new Ets2SdkClient.Ets2Telemetry._Drivetrain() ;

    static void Main(string[] args)
    {
        Program P = new Program();

       while (true)
        { 
        float m = P.a.AccelerationZ;
        float z = P.b.EngineRpmMax;
        Console.WriteLine(m);
        Console.WriteLine(z);
        }

    }

}
