### ISSUE TITLE
64 bits version

### ISSUE THREAD

**Issue by FredWatson** [nlhans/ets2-sdk-plugin#6]
Could you provide a x64 binary of your library too?

**Comment by dadragon84** [comment]
64 bits are already included 


--------------------------------------------
NOTICE:  The information contained in this email and any document attached hereto is intended only for the named recipient(s). If you are not the intended recipient, nor the employee or agent responsible for delivering this message in confidence to the intended recipient(s), you are hereby notified that you have received this transmittal in error, and any review, dissemination, distribution or copying of this transmittal or its attachments is strictly prohibited. If you have received this transmittal and/or attachments in error, please notify me immediately by reply e-mail and then delete this message, including any attachments.

--------------------------------------------

**Comment by FredWatson** [comment]
No. There is only one dll in the "ETS DLL" folder of the release (release_v1_2.zip) and it is doesn't work with the game running 64bits. (With the library in the bin/win_x64/plugins folder).

**Comment by nlhans** [comment]
I have created a x64 build in Release v1.2.1

**Comment by FredWatson** [comment]
You are awesome, thank you!
