### ISSUE TITLE
TelemetryData Event isnt working right?

### ISSUE THREAD

**Issue by Ari24-cb24** [nlhans/ets2-sdk-plugin#62]
Hey there,

I'm currently working on a litte test project and created a c# wpf application.
Now I want to know, if the game's paused or not. 

I created this little piece of code (couldn't find a documentation so I looked up into the demo) and it just dont work.

using System; 
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Ets2SdkClient;

namespace WPFSCSModding
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public Ets2SdkTelemetry Telemetry;

        public MainWindow()
        {
            InitializeComponent();

            this.Telemetry = new Ets2SdkTelemetry();
            this.Telemetry.Data += new TelemetryData(this.Telemtry_Data);
        }

        private void Telemtry_Data(Ets2Telemetry data, bool updated)
        {
            bool paused = data.Paused;
            PausedLabel.Content = "Paused: " + paused;
        }
    }
}

(edit, github's code markdown is a little bit buggy, surry)

I don't know if I'm doing anything wrong since I couldn't find a documentation about this.

Greets

**Comment by davwheat** [comment]
**Fixed code block:**

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Ets2SdkClient;

namespace WPFSCSModding
{
  /// Interaction logic for MainWindow.xaml
  ///
  public partial class MainWindow : Window
    {
        public Ets2SdkTelemetry Telemetry;
        public MainWindow()
        {
            InitializeComponent();

            this.Telemetry = new Ets2SdkTelemetry();
            this.Telemetry.Data += new TelemetryData(this.Telemtry_Data);
        }

        private void Telemtry_Data(Ets2Telemetry data, bool updated)
        {
            bool paused = data.Paused;
            PausedLabel.Content = "Paused: " + paused;
        }
    }
}
```

**Comment by Ari24-cb24** [comment]
Found something, that works fine
https://github.com/RenCloud/scs-sdk-plugin/
