### ISSUE TITLE
I cheeked and there where no notes on BUG

### ISSUE THREAD

**Issue by leedonald54** [nlhans/ets2-sdk-plugin#7]
On the new 3 axles there is note a back rear end on Volvo FH , a aqua green three axels . there is a front  axles , but you can raise  it ,and in the process you pick up the drive wheels , it works like it should ,but it is very plane to see , and so would a Company .  If you look at the pictures I put on World of Trucks you will see very easy . under leedonald54

**Comment by nlhans** [comment]
To be honest I've no idea what you're exactly talking about. But my guess is that it is some axle lift issue on the Volvo FH. 

This repository is not affiliated with SCS or ETS2, it's a fan created plug-in for ETS2 allowing developers to create their own applications on a stream of vehicle information (like speed, gear, etc. for custom dashboards etc).

I recommended starting a thread in the appropriate section at http://forum.scssoft.com/
