### ISSUE TITLE
Telemetry SDK 1.5

### ISSUE THREAD

**Issue by mkoch227** [nlhans/ets2-sdk-plugin#9]
SCS recently updated their Telemetry SDK to 1.5. Would it be possible to post the latest version here with an updated DLL? (I'm not exactly sure how to compile/build the DLL on my own)

**Comment by nlhans** [comment]
I've not started ETS2 in a couple of weeks now.

Are you talking about implementing the new SDK 1.5 features, or providing a DLL with new ETS versions? If all is right, existing DLL's should be portable to newer versions unless they broke backwards compatability in the SDK.

**Comment by mkoch227** [comment]
Good point with the DLL. I believe that the DLL is backwards-compatible, so it appears that is no longer needed. It would probably be nice though to have the demo app updated with the new channels added; however it's not a priority for me :smile:

**Comment by yodek** [comment]
At website of ETS2 I see updated link, now is SDK v1.5 - http://download.eurotrucksimulator2.com/scs_sdk_1_5.zip

**Comment by nlhans** [comment]
I've managed to get some time today after formatting my PC and changing my workflow a bit.
Release 1.3.0: https://github.com/nlhans/ets2-sdk-plugin/releases/tag/revision_4_rel_1_3_0
